/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.undotech.table.staff;

import javaswingdev.swing.table.TableCustom;
import javaswingdev.swing.table.cell.TableCustomCell;
import javaswingdev.swing.table.model.TableRowData;

/**
 *
 * @author blackundo
 */
public class Cell_ID extends TableCustomCell {

    /**
     * Creates new form Cell_ID
     */
    public Cell_ID() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void setData(Object o) {
//        txt.setText(o.toString());
    }

    @Override
    public Object getData() {
        return null;
//        return txt.getText().trim();
    }

    @Override
    public TableCustomCell createComponentCellEditor(TableCustom table, TableRowData o, Object cellData, int row, int column) {
        Cell_ID cell = new Cell_ID();
        cell.setData(o);
        return cell;
    }
}
