/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.undotech.ui;

import com.undotech.dao.ThongKeDAO;
import com.undotech.entity.ModelData;
import java.awt.Color;
import java.util.List;
import raven.chart.ModelChart;

/**
 *
 * @author blackundo
 */
public class Form_ThongKe extends javax.swing.JPanel {

    ThongKeDAO tkdao = new ThongKeDAO();
    
    public Form_ThongKe() {
        initComponents();
        chart.setTitle("Thống kê 2022");
        chart.addLegend("Tổng số Phòng", Color.decode("#7b4397"), Color.decode("#dc2430"));
        chart.addLegend("Thu nhập dịch vụ", Color.decode("#e65c00"), Color.decode("#F9D423"));
        chart.addLegend("Thu nhập Tổng", Color.decode("#0099F7"), Color.decode("#F11712"));
        setData();
    }
    
    void setData(){
        List<ModelData> list = tkdao.getdata();
        int i = 2;
        for (ModelData md : list) {
            
            chart.addData(new ModelChart(md.getMonth(),new double[]{md.getAmount(),45+i,50+i}));
            i += 5;
        }
        chart.start();
    }
    
    private void test() {
        chart.clear();
        chart.addData(new ModelChart("Tháng 1", new double[]{500, 50, 100}));
        chart.addData(new ModelChart("Tháng 2", new double[]{600, 300, 150}));
        chart.addData(new ModelChart("Tháng 3", new double[]{200, 50, 900}));
        chart.addData(new ModelChart("Tháng 4", new double[]{480, 700, 100}));
        chart.addData(new ModelChart("Tháng 5", new double[]{350, 540, 500}));
        chart.addData(new ModelChart("Tháng 6", new double[]{450, 800, 100}));
        chart.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven.panel.PanelShadow();
        chart = new raven.chart.CurveLineChart();

        panelShadow1.setBackground(new java.awt.Color(34, 59, 69));
        panelShadow1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelShadow1.setColorGradient(new java.awt.Color(17, 38, 47));

        chart.setForeground(new java.awt.Color(255, 255, 255));
        chart.setFillColor(true);

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.chart.CurveLineChart chart;
    private raven.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
