/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.undotech.ui;

import com.formdev.flatlaf.FlatLightLaf;
import com.undotech.dao.NhanVienDAO;
import com.undotech.entity.NhanVien;
import com.undotech.notification.Notification;
import com.undotech.table.staff.CellAction;
import com.undotech.table.staff.CellEmail;
import com.undotech.table.staff.CellAddress;
import com.undotech.table.staff.CellRole;
import com.undotech.table.staff.CellName;
import com.undotech.table.staff.CellTel;
import com.undotech.table.staff.Cell_ID;
import com.undotech.utils.MsgBox;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javaswingdev.swing.table.model.TableRowData;
import javax.swing.ImageIcon;

/**
 *
 * @author blackundo
 */
public class testfrom extends javax.swing.JFrame {
    NhanVienDAO dao = new NhanVienDAO();
    /**
     * Creates new form 
     */
    public testfrom() {
        FlatLightLaf.setup();
        initComponents();
        table1.addTableStyle(jScrollPane1);
        init_table();
    }
    
    private void init_table(){
        table1.addTableCell(new Cell_ID(), 0);
        table1.addTableCell(new CellName(), 1);
        table1.addTableCell(new CellRole(), 2);
        table1.addTableCell(new CellTel(), 3);
        table1.addTableCell(new CellEmail(), 4);
        table1.addTableCell(new CellAddress(), 5);
        table1.addTableCell(new CellAction(), 6);
        
//        table1.addRow(new ModelStaff(new ModelName("Ra", new ImageIcon(getClass().getResource("/com/undotech/icons/icon8_globe.png")), ""),
//                "Male", 18, "Raven123@gmail.com", "010 000 000"), false);
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    List<NhanVien> list = dao.selectBySqlform();
                    for (NhanVien nv : list) {

                        //sf.add(new ModelStaff(new ModelName(nv.getTenNV(), nv.getHinhAnh()),nv.getVaiTro(),nv.getSoDT(),nv.getEmail(),nv.getDiaChi()));

        //                Object[] rows = {nv.getTenNV(),nv.getVaiTro(),nv.getSoDT(),nv.getEmail(),nv.getDiaChi()};
                        table1.addRow( nv, false);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();


        
//        table1.editRowAt(0);

//        new Thread(new Runnable() {
//            @Override
//            public void run() {
//                try {
//                    for (NhanVien staff : new NhanVienDAO().selectAll()) {
////                        table1.addRow(staff, false);
//                        System.out.print(staff);
//                    }
//                } catch (Exception e) {
//                    System.err.println(e);
//                }
//            }
//        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javaswingdev.swing.Table();
        button1 = new javaswingdev.swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MãNV", "Tên", "Chức vụ", "sđt", "email", "địa chỉ", "hành động"
            }
        ));
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setMinWidth(50);
            table1.getColumnModel().getColumn(0).setPreferredWidth(50);
            table1.getColumnModel().getColumn(0).setMaxWidth(50);
            table1.getColumnModel().getColumn(1).setPreferredWidth(200);
            table1.getColumnModel().getColumn(2).setMinWidth(100);
            table1.getColumnModel().getColumn(2).setPreferredWidth(100);
            table1.getColumnModel().getColumn(2).setMaxWidth(100);
            table1.getColumnModel().getColumn(6).setMinWidth(75);
            table1.getColumnModel().getColumn(6).setPreferredWidth(75);
            table1.getColumnModel().getColumn(6).setMaxWidth(75);
        }

        button1.setText("Thêm mới");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
//        table1.insertRowWithEdit(new ModelStaff(new ModelName("",""),"Quản lý","","",""),0, true);
Notification noti= new Notification(this, Notification.Type.INFO, Notification.Location.BOTTOM_LEFT, "Đã thêm");

noti.showNotification();
        table1.insertRowWithEdit(new NhanVien(null, "", "", "", "", "", "", "", ""), 0, true);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testfrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testfrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testfrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testfrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testfrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.swing.Button button1;
    private javax.swing.JScrollPane jScrollPane1;
    private javaswingdev.swing.Table table1;
    // End of variables declaration//GEN-END:variables
}
