/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.undotech.ui;

import com.undotech.dao.PhongDAO;
import com.undotech.dao.TrangThaiPhongDAO;
import com.undotech.entity.Phong;
import com.undotech.entity.TrangThaiPhong;
import com.undotech.room.ModelRoom;
import com.undotech.room.Room;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author blackundo
 */
public class testphong extends javax.swing.JFrame {

    PhongDAO pdao = new PhongDAO();
    TrangThaiPhongDAO ttdao = new TrangThaiPhongDAO();
    
    
    public testphong() {
        initComponents();
        jPanel1.setLayout(new MigLayout("wrap, insets 10, fill", "[]10[]10[]","[]10[]10[]"));
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(30);
//        jScrollPane1.setLayout(new MigLayout("wrap, insets 10, fill", "[]10[]10[]","[]10[]10[]"));
        List<Phong> dsp = pdao.selectAll();
        boolean isRoomUse;
        
        for (Phong r : dsp) {
//            new com.undotech.room.Room().setModel(new ModelRoom(r.getKieuPhong(),
//                    String.valueOf(r.getGiaPhong()),
//                    String.valueOf(r.getMoTa()),
//                    new ImageIcon(getClass().getResource("/com/undotech/icons/door.png"))));
//            getContentPane().add(new com.undotech.room.Room().setModel(new ModelRoom(r.getKieuPhong(),
//                    String.valueOf(r.getGiaPhong()),
//                    r.getMoTa(),
//                    new ImageIcon(getClass().getResource("/com/undotech/icons/door.png")))));
                    if (r.getMaDatPhong() == -1) {
                        isRoomUse = true;
                    }else{
                        isRoomUse = false;
                    }
                    TrangThaiPhong tt = ttdao.selectById(r.getMaPhong());
                    
                    Room comp = new com.undotech.room.Room();
                    comp.setModel(new ModelRoom(r.getMaPhong(),r.getKieuPhong(),
                    String.valueOf(r.getGiaPhong()+"VNĐ"),
                    String.valueOf(r.getMoTa()),tt.isDonDep(),tt.isSuaChua(),isRoomUse,
                    new ImageIcon(getClass().getResource("/com/undotech/icons/door.png"))));
                    jPanel1.add(comp);
            
        }
//        for (Phong p : list) {
//            
//        }

        
        
//        room1.setModel(new ModelRoom("Rich Red Blend",
//                "35$",
//                "Java Swing tutorial is a part of Java Foundation Classes (JFC) that is used to create window-based applications. It is built on the top of AWT (Abstract Windowing Toolkit) API and entirely written in java.",
//                new ImageIcon(getClass().getResource("/com/undotech/icons/door.png"))));
//        room1.setModel(new ModelRoom("Rich Red Blend",
//                "35$",
//                "Java Swing tutorial is a part of Java Foundation Classes (JFC) that is used to create window-based applications. It is built on the top of AWT (Abstract Windowing Toolkit) API and entirely written in java.",
//                new ImageIcon(getClass().getResource("/com/undotech/icons/door.png"))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel(new MigLayout("wrap, insets 10, fill", "[]10[]10[]","[]10[]10[]"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testphong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
