/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.undotech.ui;

/**
 *
 * @author blackundo
 */
public class WelcomeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form WelcomeJDialog
     */
    public WelcomeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Loading loading = new Loading();
        setLocationRelativeTo(null);
        loading.start();
    }
    
    class Loading extends Thread {

        @Override
        public void run() {
//            txtRole.setText("Welcome 1123");
            //String userID = Auth.user.getMaNV();
            //String role = Auth.user.isVaiTro() ? "Manager" : "Employee";
    
            
            try {
                    
                for (int i = 0; i <= 100; i++) {
//                    if (i == 1) {
//                        txtRole.setText("UserID: " + userID + " |  Role: " + role);
//                    }
                    Thread.sleep(20);
                    if (i == 20) {
                        txtLoading.setText("Đang kết nối csdl...");
                    }
                    if (i == 50) {
                        txtLoading.setText("Đã kết nối...");
                    }
                    if (i == 80) {
                        txtLoading.setText("Khởi động...");
                    }
                    if (i == 100) {
//                        if (role.equalsIgnoreCase("manager")) {
//                            new StudentManagerFrame().setVisible(true);
//                        } else if (role.equalsIgnoreCase("teacher")) {
//                            new TeacherFrame().setVisible(true);
//                        }
                        dispose();
//                        new LoginJDialog(null,false).dispose();
//                        new MainJFrame().setVisible(true);
                    }
                    jProgressBar1.setValue(i);
                    txtLoadingValue.setText(i + "%");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        txtImage = new javax.swing.JLabel();
        txtLoading = new javax.swing.JLabel();
        txtLoadingValue = new javax.swing.JLabel();
        wellcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(102, 0, 102));
        jProgressBar1.setForeground(new java.awt.Color(241, 154, 135));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 643, 10));

        txtImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/undotech/icons/Infinity-1s-108px.gif"))); // NOI18N
        jPanel1.add(txtImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 80));

        txtLoading.setForeground(new java.awt.Color(0, 255, 255));
        txtLoading.setText("Loading...");
        jPanel1.add(txtLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, -1));

        txtLoadingValue.setForeground(new java.awt.Color(0, 255, 255));
        txtLoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLoadingValue.setText("0%");
        txtLoadingValue.setToolTipText("");
        jPanel1.add(txtLoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 40, -1));

        wellcome.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        wellcome.setForeground(new java.awt.Color(204, 204, 204));
        wellcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellcome.setText("Wellcome Back");
        jPanel1.add(wellcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 550, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WelcomeJDialog dialog = new WelcomeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel txtImage;
    private javax.swing.JLabel txtLoading;
    private javax.swing.JLabel txtLoadingValue;
    private javax.swing.JLabel wellcome;
    // End of variables declaration//GEN-END:variables
}
